### ISSUE TITLE
Error while building docker container #1

### ISSUE THREAD

**Issue by fardin-developer** [agtic/chronos#3]
docker-compose up --build
```
19.13 Ign:15 http://archive.raspbian.org/raspbian stretch/contrib all Packages
19.17 Fetched 218 kB in 18s (11.6 kB/s)
19.17 Reading package lists...
19.28 W: The repository 'http://archive.raspbian.org/raspbian stretch Release' does not have a Release file.
19.28 E: Failed to fetch http://archive.raspbian.org/raspbian/dists/stretch/firmware/source/Sources  404  Not Found
19.28 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c apt-get update -y && apt-get install python2.7 python-pip cron sqlite3 nginx libssl-dev vim -y" did not complete successfully: exit code: 100
```

**Comment by agtic** [comment]
Sorry @fardin-developer , I thought I commented on this last week, but I must have neglected to submit.
I've seen this error before.  It can be resolved by adding one line to the Dockerfile to add`legacy.raspbian.org`  apt sources list:
```
RUN echo "deb http://legacy.raspbian.org/raspbian stretch main contrib non-free rpi" > /etc/apt/sources.list
```

**Comment by fardin-developer** [comment]
> Sorry @fardin-developer , I thought I commented on this last week, but I must have neglected to submit. I've seen this error before. It can be resolved by adding one line to the Dockerfile to add`legacy.raspbian.org` apt sources list:
> 
> ```
> RUN echo "deb http://legacy.raspbian.org/raspbian stretch main contrib non-free rpi" > /etc/apt/sources.list
> ```

Okay, I got it.  Let me fix it and complete the task

**Comment by fardin-developer** [comment]
Hey, please check the docker file and update it. Due to this issue i am  stuck and have not solve the main isse (sepration of frontend and backend )

**Comment by fardin-developer** [comment]
> Sorry @fardin-developer , I thought I commented on this last week, but I must have neglected to submit. I've seen this error before. It can be resolved by adding one line to the Dockerfile to add`legacy.raspbian.org` apt sources list:
> 
> ```
> RUN echo "deb http://legacy.raspbian.org/raspbian stretch main contrib non-free rpi" > /etc/apt/sources.list
> ```
 
plz reply as soon as possible.......

**Comment by agtic** [comment]
Sorry for the delay @fardin-developer. I'm traveling at the moment.
I worked on it a bit today and committed a few changes directly to the master branch, but I wasn't able to finish testing them as my internet connection is a bit slow.  Feel free to try it with the changes, but I can do some more testing in the coming days.

**Comment by agtic** [comment]
Note that I've added the porting to Python 3 issue to gitpay

**Comment by agtic** [comment]
I just tried building to docker container on an Amazon EC2 instance. It takes a long them and hasn't finished yet, but it gets past the previous errors you were seeing.

**Comment by agtic** [comment]
Docker build is now working.

**Comment by agtic** [comment]
Docker build is now working. The changes were committed to the master branch directly as I'm traveling and had limited time.
